// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAhxXwxHYLn29DgGhdgd45D3kqiw9A3Po',
    appId: '1:502362084772:web:56b6f70755081a3dc29d31',
    messagingSenderId: '502362084772',
    projectId: 'push-notification-eba35',
    authDomain: 'push-notification-eba35.firebaseapp.com',
    storageBucket: 'push-notification-eba35.firebasestorage.app',
    measurementId: 'G-GWQ9BF8PTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVpQQgQM3herYCzTpm18i4ogvaDDowTs',
    appId: '1:502362084772:android:af6f9a766903ee25c29d31',
    messagingSenderId: '502362084772',
    projectId: 'push-notification-eba35',
    storageBucket: 'push-notification-eba35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYAk2QBcNqdPQxDEb2c5ewR4RpaYrEtQ',
    appId: '1:502362084772:ios:1089e5ecb31ba655c29d31',
    messagingSenderId: '502362084772',
    projectId: 'push-notification-eba35',
    storageBucket: 'push-notification-eba35.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYAk2QBcNqdPQxDEb2c5ewR4RpaYrEtQ',
    appId: '1:502362084772:ios:1089e5ecb31ba655c29d31',
    messagingSenderId: '502362084772',
    projectId: 'push-notification-eba35',
    storageBucket: 'push-notification-eba35.firebasestorage.app',
    iosBundleId: 'com.example.pushnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAhxXwxHYLn29DgGhdgd45D3kqiw9A3Po',
    appId: '1:502362084772:web:a5723493abe2cad1c29d31',
    messagingSenderId: '502362084772',
    projectId: 'push-notification-eba35',
    authDomain: 'push-notification-eba35.firebaseapp.com',
    storageBucket: 'push-notification-eba35.firebasestorage.app',
    measurementId: 'G-JY8X2SYL1E',
  );
}
